'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")>  _
Partial Friend NotInheritable Class Configuration
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Configuration = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Configuration()),Configuration)
    
    Public Shared ReadOnly Property [Default]() As Configuration
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("COM1")>  _
    Public Property PortName() As String
        Get
            Return CType(Me("PortName"),String)
        End Get
        Set
            Me("PortName") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("9600")>  _
    Public Property BaudRate() As Integer
        Get
            Return CType(Me("BaudRate"),Integer)
        End Get
        Set
            Me("BaudRate") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("none")>  _
    Public Property Parity() As String
        Get
            Return CType(Me("Parity"),String)
        End Get
        Set
            Me("Parity") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
    Public Property DataBits() As Integer
        Get
            Return CType(Me("DataBits"),Integer)
        End Get
        Set
            Me("DataBits") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property StopBits() As Integer
        Get
            Return CType(Me("StopBits"),Integer)
        End Get
        Set
            Me("StopBits") = value
        End Set
    End Property
End Class
